POST http://localhost:9999/api/auth/register
content-type: : application/json

{
    "email": "votrieuvy1661@gmail.com",
    "password": "vataweb123",
    "firstName": "Vy",
    "lastName": "CT",
    "avatar": "/images/avatars/avatar(1).svg",
    "birthDate": "16/06/2001"
}